try:
  print(12/0)
except Exception as e:
  print(e)